### PR TITLE
add tests for function IndexOf in BinarySearch with White-box testing technique, CFG and DFG

### PR DESCRIPTION
**Pull request by TeagJohn**
I have added some tests for your function by white-box testing, could you please merge them into your repos?

### CODE REVIEW

**Comment by jimmysuncpt** [comment]
Please remove files under the ".idea" directory.

**Comment by TeagJohn** [comment]
Oh, sorry, Surely, I will do it.

**Comment by TeagJohn** [comment]
Hi author, I removed the .idea folder.

**Comment by ghost** [comment]
> I have added some tests for your function by white-box testing, could you please merge them into your repos?

**Review by ghost — APPROVED** [review]

**Comment by ghost** [comment]
> I have added some tests for your function by white-box testing, could you please merge them into your repos?

publisher-production_10.10.2

**Pull request merged**
